### ISSUE TITLE
Some component's color isn't updated in light theme.

### ISSUE THREAD

**Issue by zcmgyu** [mzohaibqc/antd-theme-webpack-plugin#49]
**Describe the bug**

I tried `customize-cra` example, I realized that the component's color (hover button, progress bar, hover link color) is not updated but using default color in `light` theme. And selected item in the `Select` component is not updated in the dark theme as well.

**Show your code**

https://github.com/mzohaibqc/antd-theme-webpack-plugin/blob/master/examples/customize-cra/config-overrides.js

**Screenshots**

Light:

<img width="1552" alt="Screen Shot 2020-05-06 at 1 17 51" src="https://user-images.githubusercontent.com/13638569/81091260-ee2c2600-8f39-11ea-948a-f4d7a0d33699.png">

Dark:

<img width="402" alt="Screen Shot 2020-05-06 at 18 56 33" src="https://user-images.githubusercontent.com/13638569/81164600-94743c00-8fcb-11ea-8489-1d4d33e5bffe.png">

**Version**

>    "antd-theme-webpack-plugin": "^1.3.4",

**Comment by mzohaibqc** [comment]
@zcmgyu It's due to the fact that there is no separate color variable for handling `selected` option color for select so it's not available in dark theme (provided by Ant Design) as well so you can create a custom variable and assign that variable to that specific style like

```
@select-item-selected-option-color: #123456; // Some unique color

.ant-select-item-option-selected {
  &:not(.ant-select-item-option-disabled) {
    color: @select-item-selected-option-color;
  }
} 
```

Here is commit for al changes required for this fix and you can do the similar fix yourself for any other mismatch, it can be due to wrong color assignment in theme variables but in this issue that was not the case, it is not provided by Ant Design, so we created a new one.

https://github.com/mzohaibqc/antd-theme-webpack-plugin/commit/ab4aa4054e20d83f2c79873d6dd86d2841c5083c

![image](https://user-images.githubusercontent.com/13637803/81242818-8d7b1700-9027-11ea-8d1d-7c6862bec8a0.png)

**Comment by mzohaibqc** [comment]
@zcmgyu Here is demo
https://mzohaibqc.github.io/antd-theme-webpack-plugin/index.html

**Comment by zcmgyu** [comment]
@mzohaibqc Hi, I think that it was really helpful. Thanks for your update

**Comment by regevaz** [comment]
@mzohaibqc - can you explain why in the example at https://mzohaibqc.github.io/antd-theme-webpack-plugin/index.html when changing the value of `@btn-primary-bg` it has no effect?

**Comment by mzohaibqc** [comment]
@regevaz Wait for 1 day and I'll publish a new version with major improvements, bugs fixes and without limitation of using unique 6 digit hex colors. You could use any color or color variable or variables like `@btn-primary-bg: darken(@primary-color, 10)` etc.

Hopefully, I'll publish a new version within the next 24 hours from now

**Comment by mzohaibqc** [comment]
@regevaz Answer to your question is that, your `@btn-primary-bg` has same value as `@primary-color` (not unique) which is causing this issue. For time being (before release of new version), assign a different value to your button variable in `variables.less` file and it will work but again, this will be fixed in next version.

**Comment by regevaz** [comment]
@mzohaibqc any update regarding the new version? I noticed that some of the issues I had in my app were resolved when using the master. When are you planning to release the new version on npm?

**Comment by mzohaibqc** [comment]
@regevaz yes, new version is available `antd-theme-webpack-plugin@1.3.5` at the time of writing this. 

In order to fix button color issue, here are steps

- add respective variable in your variable file `variables.less` or whatever is name
```
@btn-primary-bg: @primary-color;
```
- Add this variable in `themeVars`,
```
themeVariables: Array.from(new Set([
    ...Object.keys(darkVars),
    ...Object.keys(lightVars),
    ...Object.keys(themeVariables), // your variables should be at the end
  ])),
```

Here is complete `config-overrides.js`, see the updated example here

https://github.com/mzohaibqc/antd-theme-webpack-plugin/tree/master/examples/customize-cra

Here is demo

https://mzohaibqc.github.io/antd-theme-webpack-plugin/

```
const path = require("path");
const fs = require("fs");
const { override, fixBabelImports, addLessLoader, addWebpackPlugin } = require('customize-cra');
// const AntDesignThemePlugin = require("antd-theme-webpack-plugin");
const AntDesignThemePlugin = require("../../index");
const { getLessVars } = require('antd-theme-generator');

const themeVariables = getLessVars(path.join(__dirname, './src/styles/vars.less'))
const defaultVars = getLessVars('./node_modules/antd/lib/style/themes/default.less')
const darkVars = { ...getLessVars('./node_modules/antd/lib/style/themes/dark.less'), '@primary-color': defaultVars['@primary-color'] };
const lightVars = { ...getLessVars('./node_modules/antd/lib/style/themes/compact.less'), '@primary-color': defaultVars['@primary-color'] };
fs.writeFileSync('./src/dark.json', JSON.stringify(darkVars));
fs.writeFileSync('./src/light.json', JSON.stringify(lightVars));
fs.writeFileSync('./src/theme.json', JSON.stringify(themeVariables));


const options = {
  stylesDir: path.join(__dirname, './src'),
  antDir: path.join(__dirname, './node_modules/antd'),
  varFile: path.join(__dirname, './src/styles/vars.less'),
  themeVariables: Array.from(new Set([
    ...Object.keys(darkVars),
    ...Object.keys(lightVars),
    ...Object.keys(themeVariables),
  ])),
  generateOnce: false, // generate color.less on each compilation
}


module.exports = override(
  fixBabelImports('import', {
    libraryName: 'antd',
    libraryDirectory: 'es',
    style: true,
  }),
  addWebpackPlugin(new AntDesignThemePlugin(options)),
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: { '@primary-color': '#25b864' },
  }),
);
```

**Comment by regevaz** [comment]
@mzohaibqc thank you for the answers and indeed it helped. I'm using the plugin now from the master branch, any chance you're going to update the npm package? currently, the latest at https://www.npmjs.com/package/antd-theme-webpack-plugin is 1.3.4 which doesn't include the latest fixes. Can you create please 1.3.5 with all the latest fixes?

**Comment by mzohaibqc** [comment]
@regevaz there is no change in master that has not been deployed to npm. New version just has updated antd-theme-generator version i.e 1.2.3 and master has same dependency. Just install v1.3.4 and compre index.js and package.json in node_module/andt-theme-webpack-plugin directory and from master

If you find any difference, let me know.
